version: '3'

services:
  astro:
    build: .
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    container_name: webserver
    restart: unless-stopped
    volumes:
      - web-root:/var/www/html
      - ./conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - astro
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email contact@whitehatchemistry.com --agree-tos --no-eff-email --force-renewal -d whitehatchemistry.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ./conf/
      o: bind


networks:
  app-network:
    driver: bridge
